<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>WinExe</OutputType>
	   <Nullable>annotations</Nullable>
		<UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MathEquationControls\MathEquationControls.csproj" />
  </ItemGroup>

</Project>
